### ISSUE TITLE
AT 13.0: Python is missing ssl module

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1269]
Test:
```
$ /opt/at13.0/bin/python3.7 -m ssl
Traceback (most recent call last):
  File "/opt/at13.0/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/at13.0/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/at13.0/lib64/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
```

Expected output: None.  Return code should be 0.

**Comment by tuliom** [comment]
AT 13.0 is the first version affected by this issue:
```
$ /opt/at11.0/bin/python3 -m ssl; echo $?
0
$ /opt/at12.0/bin/python3 -m ssl; echo $?
0
```
