### ISSUE TITLE
Error on test_ftplib on AT 13.0

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1438]
While testing PR #1395 , the Python tests found the following error:

```
0:00:44 load avg: 4.73 [192/386/1] test_ftplib crashed (Exit code -6)
Exception in thread Thread-69:
Traceback (most recent call last):
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/test/test_ftplib.py", line 378, in handle_write_event
    super(SSLConnection, self).handle_write_event()
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 441, in handle_write_event
    self.handle_write()
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asynchat.py", line 187, in handle_write
    self.initiate_send()
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asynchat.py", line 260, in initiate_send
    del self.producer_fifo[0]
IndexError: deque index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/test/test_ftplib.py", line 280, in run
    asyncore.loop(timeout=0.1, count=1)
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 156, in poll
    write(obj)
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 95, in write
    obj.handle_error()
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/test/test_ftplib.py", line 403, in handle_error
    raise Exception
Exception
double free or corruption (!prev)
Fatal Python error: Aborted
Thread 0x00007fff79d5f180 (most recent call first):
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 150 in poll
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 207 in loop
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/test/test_ftplib.py", line 280 in run
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/threading.py", line 885 in _bootstrap
Thread 0x00007fff7954f180 (most recent call first):
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/ssl.py", line 1112 in do_handshake
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/test/test_ftplib.py", line 327 in _do_ssl_handshake
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/test/test_ftplib.py", line 366 in handle_read_event
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 87 in read
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 132 in poll
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/asyncore.py", line 207 in loop
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/test/test_ftplib.py", line 280 in run
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/home/tcbot/bot-slave/at_opt/at13.0/lib64/python3.7/threading.py", line 885 in _bootstrap
Current thread 0x00007fff7a78f1python: power8:  Python crashed during the tests.
```
It's clearly unrelated to this PR and should be investigated.
I'm re-running the AT 13.0 RHEL8 ppc64le with build # 211 to confirm if this is intermittent.

**Comment by tuliom** [comment]
I think this error stopped happening. Any objections to closing this?

**Comment by mscastanho** [comment]
@tuliom We haven't been seeing this error because we disabled this test:
https://github.com/advancetoolchain/advance-toolchain/blob/f8cc209956b55d5694f480ba28f2e37deaee2a58/fvtr/python/python.exp#L146
Not sure if it's still happening or not though. But since this only affected AT 13.0, I'm fine with closing this issue too.
