### ISSUE TITLE
Sporadic failures on Python FVTR tests

### ISSUE THREAD

**Issue by mscastanho** [advancetoolchain/advance-toolchain#1471]
From time to time the AT testsuite fails when building code from our automated PRs. The failures are always on Python tests:

Usually if we run the build again, the tests pass.
 After checking the FVTR logs for these failing builds, the error seems to always be the same:
```
test test_subprocess failed -- Traceback (most recent call last):
  File "/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_subprocess.py", line 1528, in test_run_with_shell_timeout_and_capture_output
    msg="TimeoutExpired was delayed! Bad traceback:\n```\n"
AssertionError: 3.6201412540394813 not less than 1.5 : TimeoutExpired was delayed! Bad traceback:
Traceback (most recent call last):
  File "/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/python3.7/test/test_subprocess.py", line 1521, in test_run_with_shell_timeout_and_capture_output
    capture_output=True)  # New session unspecified.
  File "/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/python3.7/subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/python3.7/subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/python3.7/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/home/tcbot/bot-slave/at_opt/at-next-14.0-0-alpha/lib64/python3.7/subprocess.py", line 1011, in _check_timeout
    stderr=b''.join(stderr_seq) if stderr_seq else None)
subprocess.TimeoutExpired: Command 'sleep 3' timed out after 0.1 seconds
```

**Comment by mscastanho** [comment]
There were several recent PRs that fixed failing Python tests: #1825, #1812, #1753, #1749 
So right now most of the sporadic failing tests have been dealt with. We can reopen this in the future if needed.
