### ISSUE TITLE
FVTR failure in python (test_ssl) on AT Next on Ubuntu 16.04

### ISSUE THREAD

**Issue by gftg85** [advancetoolchain/advance-toolchain#201]
Building AT Next on Ubuntu 16.04 causes a FVTR failure in python's test for SSL (test_ssl).

This is the error message:

```
0:01:54 [290/391/1] test_ssl failed -- running: test_multiprocessing_spawn (56 sec), test_multiprocessing_forkserver (63 sec)
Exception in thread Thread-83:
Traceback (most recent call last):
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/test/test_ssl.py", line 1926, in run
    if not self.wrap_conn():
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/test/test_ssl.py", line 1871, in wrap_conn
    self.sock, server_side=True)
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

test test_ssl failed -- Traceback (most recent call last):
  File "/home/gftg/opt/at-next-12.0-0-alpha/lib64/python3.6/test/test_ssl.py", line 241, in test_random_fork
    self.assertNotEqual(child_random, parent_random)
AssertionError: b')\x8e\xb3[\xd56\xd1\x838\x93P\xdb=\nb>' == b')\x8e\xb3[\xd56\xd1\x838\x93P\xdb=\nb>'
[...]
1 test failed:
    test_ssl
```

This is **not** related to pull request #178.

**Comment by tuliom** [comment]
It seems to be related to [Python issue #28689](https://bugs.python.org/issue28689).
