### ISSUE TITLE
[FVTR] Python test_socket is failing on ppc64 for AT 11.0

### ISSUE THREAD

**Issue by rzinsly** [advancetoolchain/advance-toolchain#251]
Observed on RHEL7 ppc64:
```
0:02:09 load avg: 2.13 [329/391] test_tools passed -- running: test_multiprocessing_spawn (75 sec)
0:02:09 load avg: 2.13 [330/391/1] test_socket failed -- running: test_multiprocessing_spawn (75 sec)
test test_socket failed -- Traceback (most recent call last):
  File "/opt/at11.0-2-rc1/lib64/python3.6/test/test_socket.py", line 5424, in test_sha256
    op.sendall(b"abc")
OSError: [Errno 126] Required key not available
0:02:09 load avg: 2.12 [331/391/1] test_tokenize passed -- running: test_multiprocessing_spawn (76 sec)
```

Running in verbose mode:
```
======================================================================
ERROR: test_sha256 (test.test_socket.LinuxKernelCryptoAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rzinsly/AT/opt/at11.0/lib64/python3.6/test/test_socket.py", line 5
424, in test_sha256
    op.sendall(b"abc")
OSError: [Errno 126] Required key not available
 ```

It seems related to [Python issue #31705](https://bugs.python.org/issue31705)

**Comment by rzinsly** [comment]
Python commit https://github.com/python/cpython/commit/92a2c07b71aefc01f84ba4b0eda8e2a45c1a6b65 fixes the issue.
We need to update Python on AT 11.0.

**Comment by rzinsly** [comment]
Done by https://github.com/advancetoolchain/advance-toolchain/commit/a148ca8768f3626c2772b00df7416658fe56044c
